title: All the Color in the World
email:  info@aparallax.com
description: >-
  A limited edition by Christopher Adams and Jun Yang
url: "https://aparallax.github.io/allthecolorintheworld/"

baseurl: "/allthecolorintheworld"

author: Christopher Adams and Jun Yang

twitter_url: https://twitter.com/christopheradam

collections:
  colors:
    output: true

defaults:
  - scope:
      path: ""
      type: "colors"
    values:
      layout: "123"
      permalink: /colors/123/:name

# Build settings
plugins:
  - jekyll-feed


exclude:
  - CNAME
  - README.md
