title: All the Color in the World
email: info@allthecolorintheworld.com
description: >-
  A project by Christopher Adams and Jun Yang
url: "https://allthecolorintheworld.com"

author: Christopher Adams and Jun Yang

github_url: https://github.com/christopheradams/allthecolorintheworld.com
twitter_url: https://twitter.com/christopheradam

signup_url: https://formspree.io/f/mgepdday

collections:
  colors:
    output: true

defaults:
  - scope:
      path: ""
      type: "colors"
    values:
      layout: "123"
      permalink: /colors/123/:name

# Build settings
plugins:
  - jekyll-feed
