title: All the Color in the World
email: info@allthecolorintheworld.com
description: >-
  A project by Christopher Adams and Jun Yang
url: "https://allthecolorintheworld.com"

author: Christopher Adams and Jun Yang

github_url: https://github.com/christopheradams/allthecolorintheworld.com

# Build settings
plugins:
  - jekyll-feed
