title: All the Color in the World
email: info@allthecolorintheworld.com
description: >-
  A project by Christopher Adams and Jun Yang
url: "https://allthecolorintheworld.com"

author: Christopher Adams and Jun Yang

github_url: https://github.com/christopheradams/allthecolorintheworld.com

signup_url: https://formspree.io/f/mgepdday

background_images:
  - url: assets/images/all-the-color_ol-1.jpeg
    alignment: center
  - url: assets/images/all-the-color_ol-2.jpeg
    alignment: top
  - url: assets/images/all-the-color_ol-3.jpeg
    alignment: center

# Build settings
plugins:
  - jekyll-feed
